[package]
name = "dex-math"
version = "0.1.4"
edition = "2021"

[lib]
name = "dex_math"
path = "src/lib.rs"

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
borsh = "0.10"

[dev-dependencies]
proptest = "1.7.0"
spl-math = { version = "0.3.0", features = ["no-entrypoint"] }
